name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go toolchain
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'  # specify the Go version you want to use

    - name: Build the app
      run: ./scripts/buildprod.sh

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure gcloud
      run: gcloud config set project cedar-catfish-443215-u7

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy notely \
          --image us-central1-docker.pkg.dev/cedar-catfish-443215-u7/notely-ar-repo/notely:latest \
          --region us-central1 \
          --allow-unauthenticated \
          --project cedar-catfish-443215-u7 \
          --max-instances=4

