name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go toolchain
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # specify the Go version you want to use

    - name: Build the app
      run: ./scripts/buildprod.sh
