name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test ./...

      # Install gosec for security checks
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      # Run gosec to check for security vulnerabilities
      - name: Run gosec
        run: gosec ./...

